#! /usr/bin/env bash

##############################################################################
#_____  _______      _     ____           ____
#‾‾‾‾‾##‾‾‾‾‾‾####$'‾‾‾'$###,‾‾';#######:'‾‾,# Copyright Benoit CORSO - 2024
#%   %###%   %###    ,    ###%,  ;#####:  ,%## benoit.corso@laplateforme.io
#%     %#%   %##    %#%    ####%,  ;#:  ,%#### Edité le: 2024-09-04 23:12
#%   %   %   %##    $@$    ######%     %######
#%   %#%     %##    %#%    ####%'  ;#:  '%#### Projet: Secu Entreprise
#%   %###%   %###    '    ###%'  ;#####:  '%## Fichier: install
#______##_____####$,___,$###'__,;#######:,__'# 
#‾‾‾‾‾‾  ‾‾‾‾‾‾      ‾     ‾‾‾‾           ‾‾‾‾
###############################################################################
#
# Ce script permet d'installer l'ensemble du projet secu entreprise
# Vous pouvez le configurer en entrant les variables d'environnement ci-dessous
# 	de meme pour les versions des paquets.
#
# Le script a pour but d'automatiser l'installation avec des parametres
# 	qui n'expose pas les données collectés par les differents services.
#
# Configuration:
ARCH=${ARCH:=arm64}
OS=${OS:=linux}
DISTRO=${DISTRO:=debian}
WINDOWS_ARCH=${WINDOWS_ARCH:=amd64}
MACOS_ARCH=${MACOS_ARCH:=arm64}

declare -A packages
packages=(
	["zabbix"]		="${ZABBIX_VERSION:=7.0}"	#LTS
	["prometheus"]		="${PROMETHEUS_VERSION:=2.54.1}"#2024-08-27
	["node_exporter"]	="${NODEEXP_VERSION:=1.8.2}"	#2024-06-19
	["windows_exporter"]	="${WINDOWSEXP_VERSION:=0.28.1}"#2024-08-31
	["grafana"]		="${GRAFANA_VERSION:=}"		#
	["elasticsearch"]	="${ELASTIC_VERSION:=}"		#
	["kibana"]		="${KIBANA_VERSION:=}"		#
	["metricbeat"]		="${METRIC_VERSION:=}"		#
	["logstash"]		="${LOGSTASH_VERSION:=}"	#
	["thehive"]		="${THEHIVE_VERSION:=}"		#
	["mariadb"]		="${MARIADB_VERSION:=}"		#
	["nginx"]		="${NGINX_VERSION:=}"		#
	["MISP"]		="${MISP_VERSION:=}"		#
)

# Fin de la configuration
##############################################################################
unset VERSION
unset version

gh_prometheus="https://github.com/prometheus/"
gh_prometheus_community="https://github.com/prometheus-community/"

get_installer() {
	local version=$1
	local 
	installers=(
		"https://repo.zabbix.com/"
		"${gh_prometheus}"
	#	"${gh_prometheus}"
	#	"${gh_prometheus_community}"
		""
	)
}

install_deb() {
	local install=$2
	local package=$1
	dpkg -i "${install}"
	if [ "$?" = "0" ]; then
		echo "${package} installation complete."
	fi
	rm "${install}"
}

install_tar() {
	local install=$2
	local package=$1
	local binary=${3:=$1}
	tar xvf "${install}" -C "/tmp/${package}"
	if [ "$?" = "0" ]; then
		echo "${package} installation complete."
	fi
}

make_unit() {
	service_name=$1
	service_user=$2
	service_group=$3
	description=$4
	binary=$5
	cat <<EOF>"/etc/systemd/system/$1.service"
[Unit]
Description=Prometheus Monitoring
Wants=network-online.target
After=network-online.target

[Service]
User=prometheus
Group=prometheus
Type=simple
ExecStart=/usr/local/bin/prometheus \
     --config.file /etc/prometheus/prometheus.yml \
     --storage.tsdb.path /var/lib/prometheus/ \
     --web.console.templates=/etc/prometheus/consoles \
     --web.console.libraries=/etc/prometheus/console_libraries

[Install]
WantedBy=multi-user.target
EOF
}

print_help() {
	echo ""
}

for arg in "$@"; do
	case $arg in
		"--help")
		"-h"
		print_help;;
	*) echo >&2 "Invalid option: $@"; exit 1;;
	esac
done


i=((0))
for package in "${packages[@]}"; do
	echo "Installing ${package} v${version[$i]}"
	((i++))
done
